accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login,logout
from accounts import views


urlpatterns = [
    url(r'^login/$', login,
        {'template_name': 'accounts/login.html'},
        name='login'),
    url(r'^logout/$', logout,
        {'template_name': 'accounts/logged_out.html'},
        name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^profile/(?P<user_id>\d+)/$', views.profile, name='profile'),
    url(r'^edit/$', views.edit, name='edit'),
]

django_twitter/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^twitter/', include('twitter.urls', namespace='twitter')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

twitter/urls.py
from django.conf.urls import url
from twitter import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^delete/(?P<tweet_id>\d+)/$', views.twi_delete, name='twi_delete'),
    url(r'^reply/(?P<tweet_id>\d+)/$', views.reqly, name='reply'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Ex_User(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image_url = models.CharField(max_length=100)
    image_file = models.CharField(max_length=100)
    profile = models.TextField(max_length=140)

twitter/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Tweet(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    reply_tweet_id = models.IntegerField(null=True, blank=True)
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(default=timezone.now)



class Favorite(models.Model):
    tweet_id = models.ForeignKey(Tweet, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and User.objects.filter(email=email).count():
            raise forms.ValidationError(u'すでに登録済みのメールアドレスです')
        return email


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', )

twitter/forms.py
from django.forms import ModelForm
from django import forms
from twitter.models import Tweet

class TweetForm(forms.ModelForm):
    """ツイートのフォーム"""
    class Meta:
        model = Tweet
        fields = ('content', )

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from accounts.forms import SignupForm, UserEditForm
from django.contrib.auth.models import User
from twitter.models import Tweet, Favorite
from django.contrib import messages
from django.core.paginator import Paginator
from django.core.mail import send_mail, EmailMessage
from django_twitter import settings


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        # return HttpResponse(request.POST['email'])
        if form.is_valid():
            form.save()
            # メールの送信(他の処理に分けた方が良いかも???)
            subject = "twitterユーザ作成メール"
            message = "ユーザを作成しました"
            from_email = settings.EMAIL_HOST
            recipient_list = [request.POST['email']]
            send_mail(subject, message, from_email, recipient_list)
            # メールの送信ここまで
            
            messages.success(request, 'ユーザを作成しました')
            return redirect('/accounts/login')
        else:
            context = {
                'form': form,
            }
            return render(request, 'accounts/signup.html', context)
    else:
        form = SignupForm(request.POST or None)
        context = {
            'form': form,
        }
        return render(request, 'accounts/signup.html', context)



@login_required
def profile(request, user_id):
    get_user = get_object_or_404(User, pk=user_id)
    tweets = Tweet.objects.filter(user_id_id=user_id).order_by('-id')
    return render(request, 'accounts/profile.html', dict(get_user=get_user, tweets=tweets))


@login_required
def edit(request):
    login_user = request.user

    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=login_user)
        if form.is_valid():
            user = form.save(commit=False)
            user.id = request.user.id
            user.save()
            messages.success(request, '更新しました！')
            return redirect('accounts:profile', user_id=login_user.id)
    else:
        form = UserEditForm(instance=login_user)

    return render(request, 'accounts/edit.html', dict(login_user=login_user, form = form))


@login_required
def delete(request):
    return HttpResponse('User削除')

twitter/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from twitter.models import Tweet, Favorite
from django.contrib.auth.models import User
from twitter.forms import *
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required
def index(request):
    if request.method == 'POST':
        form = TweetForm(request.POST)
        if form.is_valid():
            tweet = form.save(commit=False)
            tweet.user_id_id = request.user.id
            tweet.save()
            return redirect('twitter:index')
    else:
        form = TweetForm()

    tweet_list = Tweet.objects.select_related().all().order_by('-id')

    #ページネーションの設定
    paginator = Paginator(tweet_list, 5)
    page = request.GET.get('page')
    try:
        tweets = paginator.page(page)
    except PageNotAnInteger:
        tweets = paginator.page(1)
    except EmptyPage:
        tweets = paginator.page(paginator.num_pages)

    return render(request,
        'twitter/index.html',
        dict(tweets=tweets, form=form)
    )


@login_required
def reqly(request, tweet_id):
    Tweet = get_object_or_404(Twitter, pk=tweet_id)


@login_required
def twi_delete(request, tweet_id):
    tweet = get_object_or_404(Tweet, pk=tweet_id)
    tweet.delete()
    messages.success(request, '削除しました')
    return redirect('twitter:index')

accounts/templates/accounts/edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}ユーザ情報編集{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
<form action="{% url 'accounts:edit' %}" method="post" class="form-horizontal" role="form">
    {% csrf_token %}
    <div class="form-group">
    {{ form|bootstrap }}
    </div>
    <div class="form-group">
        <div>
            <input type="submit" class="btn btn-primary" value="編集する">
        </div>
    </div>
</form>
</div>
{% endblock %}

accounts/templates/accounts/logged_out.html
{% extends "base.html" %}

{% block title %}ログアウト{% endblock title %}

{% block content %}

<h3 class="page-header">ログアウトしました</h3>

<div>
  <a href="{% url 'accounts:login' %}">ログイン</a>
</div>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block title %}Twitterにログイン{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}


{% block content %}

{% if form.errors  %}
  <div class="alert alert-danger" role="alert">
    <p>ユーザ名かパスワードが間違っています</p>
  </div>
{% endif %}

<h2>ログイン</h2>
<form method="post" role="form" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
        <input id="id_username" name="username" type="text" value="" maxlength="256" placeholder="ユーザ名を入力" class="form-control"/>
    </div>
    <div class="form-group">
        <input id="id_password" name="password" type="password" value="" maxlength="256" placeholder="パスワードを入力" class="form-control"/>
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
    <input name="next" type="hidden" value="{{ next }}"/>
</form>


{% endblock %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block title %}profile{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
<!-- プロフィール表示部 -->
<h2>@{{ get_user.username }}</h2>
<small>登録日時:{{ get_user.date_joined }}</small><br>
<small>最終ログイン日時:{{ get_user.last_login }}</small>
{% if get_user.id == user.id %}
<div style="margin-top:30px;">
    <a href="{% url 'accounts:edit' %}">プロフィールを編集する</a>
<div>
{% endif %}
<hr>

<!-- ツイート表示部 -->
<h4>ツイート一覧</h4>
{% include "tweet_list.html" %}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block title %}新規ユーザ登録{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
<h2>新規ユーザ登録</h2>
<form method="post" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_username">ユーザネーム</label>
        {{ form.username }}
        {{ form.username.errors }}
    </div>
    <div class="form-group">
        <label for="email">メールアドレス</label>
        {{ form.email }}
        {{ form.email.errors }}
    </div>
    <div class="form-group">
        <label for="id_password1">パスワード</label>
        {{ form.password1 }}
        {{ form.password1.errors }}
    </div>
    <div class="form-group">
    <label control-label for="id_password2">パスワード（確認）</label>
        {{ form.password2 }}
        {{ form.password2.errors }}
        <p class="help-block">{{ form.password2.help_text }}</p>
    </div>
    <div class="form-group">
        <div>
            <input type="submit" class="btn btn-primary" value="登録">
        </div>
    </div>
</form>

{% endblock %}

accounts/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Twitter{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block extrahead %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'twitter:index' %}">Twitter</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'accounts:profile' user_id=user.id %}">プロフィール</a></li>
                    <li><a href="{% url 'accounts:logout' %}">ログアウト</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">ログイン</a></li>
                    <li><a href="{% url 'accounts:signup' %}">新規登録</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
      {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
      {% endif %}
        {% block content %}
          {{ content }}
        {% endblock %}
    </div>
</body>
</html>

accounts/templates/tweet_list.html
<script>
$(function() {
  $('.tweet_reply').on('click', function () {
     $("#reply_content").text($(this).attr("content"));
     $("#reply_user").text($(this).attr("user"));
     $("#tweet_created_at").text($(this).attr("created_at"));
  });
});
</script>
{% if tweets %}
    {% for tweet in tweets %}
          <div class="panel panel-primary">
              <div class="panel-body">
                @<a href="{% url 'accounts:profile' user_id=tweet.user_id_id %}">{{ tweet.user_id }}</a>&nbsp;&nbsp;{{ tweet.created_at }}<br>
                {{ tweet.content }}<br>
                <a
                  class="tweet_reply"
                  data-toggle="modal"
                  data-target="#replyModal"
                  id="{{ tweet.id }}"
                  content="{{ tweet.content }}"
                  user="{{ tweet.user_id }}"
                  user_id="{{ tweet.user_id_id }}"
                  created_at="{{ tweet.created_at }}"
                  href="{% url 'twitter:reply' tweet_id=tweet.id %}">返信する</a>&nbsp;
                {% if tweet.user_id_id == user.id %}
                <a href="{% url 'twitter:twi_delete' tweet_id=tweet.id %}">削除する</a>
                {% endif %}
              </div>
          </div>
    {% endfor %}
{% else %}
    <p>まだ何もありません</p>
{% endif %}

<ul class="pagination">
    {% if tweets.has_previous %}
        <li><a href="?page={{ tweets.previous_page_number }}">&laquo;</a></li>
    {% else %}
        <li class="disabled"><a href="#">&laquo;</a></li>
    {% endif %}

    {% for linkpage in tweets.paginator.page_range %}
        {% ifequal linkpage tweets.number %}
            <li  class="active"><a href="#">{{ linkpage }}</a></li>
        {% else %}
            <li><a href="?page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
    {% endfor %}

    {% if tweets.has_next %}
        <li><a href="?page={{ tweets.next_page_number }}">&raquo;</a></li>
    {% else %}
        <li class="disabled"><a href="#">&raquo;</a></li>
    {% endif %}
</ul>

{# リプライ用のモーダル ダイアログ #}
<div class="modal fade" id="replyModal" tabindex="-1" role="dialog" aria-labelledby="replyModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="replyModalLabel">ツイートに返信する</h4>
      </div>
      <div class="modal-body">
        <div class="panel panel-primary">
            <div class="panel-body">
                @<a href="{% url 'accounts:profile' user_id=1 %}"><span id="reply_user"></span></a>
                &nbsp;&nbsp;
                <span id="tweet_created_at"></span><br>
                <span id="reply_content"></span>
            </div>
        </div>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-primary" id="reply_url">返信する</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

twitter/templates/twitter/index.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}Twitter{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
<!-- twitterのつぶやきフォーム -->
<div class="row">
    <form action="{% url 'twitter:index' %}" method="post" class="form-horizontal" role="form">
        {% csrf_token %}
        <div class="form-group">
        {{ form|bootstrap }}
        </div>
        <div class="form-group">
            <div>
                <input type="submit" class="btn btn-primary" value="つぶやく">
            </div>
        </div>
    </form>
</div>

<!-- twitterのつぶやき表示 -->
<div class="row">
  {% include "tweet_list.html" %}
</div>
{% endblock %}